// <auto-generated />
namespace Qalsql.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class merge_as_one_db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(merge_as_one_db));
        
        string IMigrationMetadata.Id
        {
            get { return "201612082148122_merge_as_one_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
