// <auto-generated />
namespace Qalsql.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class message_for_answer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(message_for_answer));
        
        string IMigrationMetadata.Id
        {
            get { return "201612161218201_message_for_answer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
