// <auto-generated />
namespace Qalsql.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class extend_app_user_data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(extend_app_user_data));
        
        string IMigrationMetadata.Id
        {
            get { return "201612082032158_extend_app_user_data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
